operator:
  name: composable-resource-operator
  systemNamespace: composable-resource-operator-system
  controllerSA: composable-resource-operator-controller-manager
  replicas: 1

image: "10.38.251.227:5000/cdi-operator:latest"
imagePullPolicy: IfNotPresent

webhook:
  tls:
    secretName: webhook-server-cert
    crt: |
      -----BEGIN CERTIFICATE-----
      MIIERzCCAy+gAwIBAgIUW5ZV/bSYz7P1H+Xu00M7EcFW0+QwDQYJKoZIhvcNAQEL
      BQAwNzE1MDMGA1UEAwwsY29tcG9zYWJsZS1yZXNvdXJjZS1vcGVyYXRvci13ZWJo
      b29rLXNlcnZpY2UwHhcNMjUxMDE0MTAzNjUwWhcNMjYxMDE0MTAzNjUwWjA3MTUw
      MwYDVQQDDCxjb21wb3NhYmxlLXJlc291cmNlLW9wZXJhdG9yLXdlYmhvb2stc2Vy
      dmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOCupppfZVgcoRIy
      kl3skHdk7jRALhoE2/AHqTJXSWqPCVEKIKB5LLAvFkxpiy+tHpPiq1CYdkcyoo2S
      Y7rrV0IwSzqMMUpMqDXy7bwFSIoJfSqA6MF3LhT8LjeNtCf0WxUgof34WzIlPIBD
      wshg4l1d27JHZoKNiKZ+4Q+c6DLwspBkFAs2LcT7PRYbF9Ya/mNdbSNxcnxXAaL+
      sV/qZSYA0l5KbIEse82MkKhS54MnfPdBzSQCJwimZEmYSDaX9AjpktdaHGsUJ16C
      jb3EgtgsLkHguT4+pb4xbGsnwcccxFXiyYNOYMcfVVFtfJs8b3sUL/nHFRaejKwf
      urW+ou0CAwEAAaOCAUkwggFFMB0GA1UdDgQWBBTw8NEj7gcTApR8GQCU9ZpA1GDh
      1zAfBgNVHSMEGDAWgBTw8NEj7gcTApR8GQCU9ZpA1GDh1zCBxQYDVR0RBIG9MIG6
      glRjb21wb3NhYmxlLXJlc291cmNlLW9wZXJhdG9yLXdlYmhvb2stc2VydmljZS5j
      b21wb3NhYmxlLXJlc291cmNlLW9wZXJhdG9yLXN5c3RlbS5zdmOCYmNvbXBvc2Fi
      bGUtcmVzb3VyY2Utb3BlcmF0b3Itd2ViaG9vay1zZXJ2aWNlLmNvbXBvc2FibGUt
      cmVzb3VyY2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsMAwGA1Ud
      EwEB/wQCMAAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
      BgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAHdSZRwJpYblk4wyRfnfkWZb8uYoE
      FQ95pyPj55om8gi9U4gOp9puPVOrgaG9gYuGrOzr64oV4bihs5SHSCH5Y4/ojumn
      WMS+vKRpw7jzpXT7BvLz+M2lbAHciUxKvgwsKU6wGnS5EHfUhOhlmYQIlVHtJo+u
      ydojxJYvRY36SLDzT8OTJ6F/T/qNnNx58XAfxtBNMC2kt3/RmG1wnQhu7UTVyzT2
      Kf1tLtdY+TokKmOMfQNpCINLI0F7xDu1bf1NWrSj7ZeK57TR9MerkJn275tPEotv
      rW/yHBhyNqJ7X0dPlyMZqSz7cxxCZnDtTWbPlAVy8DWL9XKHHAojhFhcCg==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDgrqaaX2VYHKES
      MpJd7JB3ZO40QC4aBNvwB6kyV0lqjwlRCiCgeSywLxZMaYsvrR6T4qtQmHZHMqKN
      kmO661dCMEs6jDFKTKg18u28BUiKCX0qgOjBdy4U/C43jbQn9FsVIKH9+FsyJTyA
      Q8LIYOJdXduyR2aCjYimfuEPnOgy8LKQZBQLNi3E+z0WGxfWGv5jXW0jcXJ8VwGi
      /rFf6mUmANJeSmyBLHvNjJCoUueDJ3z3Qc0kAicIpmRJmEg2l/QI6ZLXWhxrFCde
      go29xILYLC5B4Lk+PqW+MWxrJ8HHHMRV4smDTmDHH1VRbXybPG97FC/5xxUWnoys
      H7q1vqLtAgMBAAECggEAP/ssIUCyJNW+PmbdTFbNytoYhROTrUAd+2vLEDVQCEKk
      JgoqwVfQVHmMMYVKp/B2CSnenAxWfi7aoFMECFn1FrmW6py6eox6yCYd8dFVV02d
      cYmU/ma4Xixz4sj8+PW6LDmHN8HOAmkdIe9p29LPE0RjiBCSDfJM7BCseVw2uS5O
      KqDioagGYq3I8EdVkpVHruAZ9wqI7WzPv/KNsGzKbkzhLVsel4emwN44P8It0slT
      VGWkRDVKuJCYi+AkQpe5RsgLyo5EgzfwqJFlpwyrL9Ony/NoG2z2GcHRQDU1ZQst
      6MDESpQJ/ykfDLqbl8L7FC+exV0cfg197U7BonTalwKBgQDxoxk8ex59kO6bYBr7
      tobwtZPYCZm3brFCZr8SbRm4W89giGFmcTCzmmKbmQaAa6pAIAg04rGKQfudvlTJ
      2ikXtuDI2M+3eFuauJyfnzcskTdIEzC9z99gSXgIeyMdrphx6aDplFDpZGr3u0SZ
      kuctECIZshGA0Y1BLxQFiRNfEwKBgQDuCY5le2JRI6lg0fWhwITmIu/AzW4ijR6W
      bDUCNuGCFGEQk4xrKEDGwl+VaLPGh9pSbcQzDrX2yM16mutfGlYTPqBwr6T8BjpE
      6b5PudI6qgoJMAWnLnZLpzgHYSHGdgwvovkxWR+g3TSpOd/E2y5vRy6KO6rFmhvE
      spwFmKw1/wKBgCMRP21WlNM2QFqONPxIvgaa42zb39IOH216ico7yRrHQC5LPI9o
      Z9/4zMy2BYqHlXqe63H5YDinYMPAxn9QyNvnL3IWfPasYebvWdOUgKZYIMS1/EHf
      tBQ+NUxNyofZOch2VmLvolpst1VieQ8skZ4plDlUbVPblXtbQLWY8hW/AoGAfyU/
      mFlFdM21pW/A4ntxAXRb2AJi97WlRvfZgKtL3S2Bg1csw/gmUYR1hdr9W+go56qW
      CCetbnpntzuUyaHJpFHpZQeM+slgynqIGxHIh2lYHvw1qM0ahuJ0/QwW/GkFrVRC
      Auf2CvjdLh8ptX7V2L6Oz2t7ljzw5Cn7SMn6AoUCgYAZe1m6UxVXGjM9baY3FbyN
      mSdUxTwUDL0HT938CCNt96K3IJj69zM23+cMBvzhRdoFP4skm5ZPnIemVXy4EEPk
      0dQkf8ihLCa3Xt+Rq8i06G7kydB/D/pGcbdXJ3+9brh+kBhVPgGNhQ2svLZUZ7Vp
      xFIhKfAUCp9cqgBwga0zVw==
      -----END PRIVATE KEY-----

managerEnv:
  CDI_PROVIDER_TYPE: "FTI_CDI"
  DEVICE_RESOURCE_TYPE: "DRA"
  FTI_CDI_API_TYPE: "FM"
  FTI_CDI_ENDPOINT: "192.168.1.101:443"
  SSL_CERT_FILE: "/etc/ssl/certs/custom-ca/ca.crt"
