apiVersion: v1
kind: ConfigMap
metadata:
  name: composable-dra-dds
  namespace: composable-dra
data:
  label-prefix: {{ .Values.global.configData.labelPrefix | quote }}
  fabric-id-range: {{ .Values.global.configData.fabricIdRange | quote }}
  device-info: |
{{- nindent 4 .Values.global.configData.deviceInfo }}
