apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  label-prefix: {{ .Values.global.configData.labelPrefix | quote }}
  fabric-id-range: {{ .Values.global.configData.fabricIdRange | quote }}
  device-info: |
{{- nindent 4 .Values.global.configData.deviceInfo }}
