apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
stringData:
  username: {{ .Values.secret.username | quote }}
  password: {{ .Values.secret.password | quote }}
  realm: {{ .Values.secret.realm | quote }}
  client_id: {{ .Values.secret.client_id | quote }}
  client_secret: {{ .Values.secret.client_secret | quote }}
  certificate: |
{{- nindent 4 .Values.secret.certificate }}
