---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamic-device-scaler-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - patch
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composableresources
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceslices
  verbs:
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims/status
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dynamic-device-scaler
  name: dds-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynamic-device-scaler-role
subjects:
- kind: ServiceAccount
  name: dds-controller-manager
  namespace: composable-dra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: dynamic-device-scaler
  name: dds-controller-manager
  namespace: composable-dra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dds-controller-manager
  namespace: composable-dra
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: dynamic-device-scaler
        image: 10.38.251.227:5000/dds:latest
        imagePullPolicy: IfNotPresent
        command: ["/dynamic-device-scaler"]
        args: ["--log-level=debug"]
        env:
        - name: SCAN_INTERVAL
          value: "10"
      serviceAccountName: dds-controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynamic-device-scaler-configmap-reader
  namespace: composable-dra
  labels:
    app.kubernetes.io/name: dynamic-device-scaler
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["composable-dra-dds"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynamic-device-scaler-configmap-readerbinding
  namespace: composable-dra
  labels:
    app.kubernetes.io/name: dynamic-device-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynamic-device-scaler-configmap-reader
subjects:
- kind: ServiceAccount
  name: dds-controller-manager
  namespace: composable-dra
---
