# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - feature-2281
  - feature-2281-*

pool:
  vmImage: ubuntu-latest

steps:
  - task: HelmInstaller@1
    displayName: Helm installer
    inputs:
      helmVersionToInstall: latest

  - script: helm lint --strict CoHDI/
    displayName: "Run helm lint"

  - script: helm template --generate-name --debug CoHDI
    displayName: "Generate template locally"

  - task: ShellScript@2
    inputs:
      scriptPath: "run_all_helm_tests.sh"
    displayName: "Run all Helm unit tests"
