global:
  env:
    CDI_ENDPOINT: "https://cdimgr.localdomain"
    CLUSTER_ID: ""
    TENANT_ID: "060ea5a5-46e4-42b4-8d95-70578718d8d0"

  credentials:
    username: "tenant3-user"
    password: "CDI@dm1n"
    realm: "060ea5a5-46e4-42b4-8d95-70578718d8d0"
    client_id: "cdi"
    client_secret: "Zmet0q6Xjno0xzaAr76IH2IYr7DfScZj"
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDkjCCAnqgAwIBAgIUaSicFyqWGzZijlylo5oggwM9EoUwDQYJKoZIhvcNAQEL
      BQAwXzELMAkGA1UEBhMCSlAxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTEcMBoGA1UE
      CgwTRGVmYXVsdCBDb21wYW55IEx0ZDEbMBkGA1UEAwwSY2RpbWdyLmxvY2FsZG9t
      YWluMB4XDTI1MDkyOTA2MjcxNFoXDTI2MDkyOTA2MjcxNFowXzELMAkGA1UEBhMC
      SlAxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTEcMBoGA1UECgwTRGVmYXVsdCBDb21w
      YW55IEx0ZDEbMBkGA1UEAwwSY2RpbWdyLmxvY2FsZG9tYWluMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEApjorwHE2za1kN1wTaseUvkrwl92LpqFi8lJb
      anafDq4t6csyieI+vdZtxFM6QybguzgnAjVh3ANDK6Gs8+i4wAMfnLW2QANhGivc
      xajtSrZ+ODShrc+/6RGkgk834iNcp6rPZ2z/0vzydBqXjK+UIJdmY5VRLc6tCVdE
      8rQ3LTYn+aihu5hzuFGectHfoUoM5w5m67u+h+kzbeOQ7GdkMaRKS0+0sbDBC+Ex
      IOZIoqj4uXvZmGeRXqg9Hp9n9CX5b3mQpJVFU7efdKFSBOwJFJ/dqShW8k15NgsO
      XquwPWoZVA13sJbRqZOttxd+ZSKVboq1DPV8W5h9jFM9UxcYCQIDAQABo0YwRDAj
      BgNVHREEHDAaghJjZGltZ3IubG9jYWxkb21haW6HBMCoAWUwHQYDVR0OBBYEFOj6
      MP36fo1v0JWiZIPmYMIriA2GMA0GCSqGSIb3DQEBCwUAA4IBAQAFe8aYj3KLZOkR
      FuPxQglVS9mKvBxkKnJzkBPawkDsaEzcoc4mDpPD79gsGY+dcdXhv6XyOHWquxZF
      4nMkcOibzi+Hra86i2SzFlMTzUHRytlvVtPWmtixK25I0od8mmoJmS/m+W+Tplcy
      rJfUzsYxGn90Q+MEpzl1TGgaTxftmPP8xgggsJmALdVr9AWudWQYHtDhAFuD/WZv
      bohsVJazIhOhw6H+40G1HdfZwc9L/aM/YTwVPFhFIYQx38eaDfarZMcbwUTvCUd/
      oGlPMtMaazOucBSj4q0WpBKEkxakVb7SeWaK5v5KdfVMR+ovmCPmSJTkTWjAPGQu
      qZBlmIPE
      -----END CERTIFICATE-----

  externalCA:
    secretName: external-server-ca-cert
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lVTW55WEVkSmhYamdqNE9qQ0JUNVYvNXN2VWdFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF3d09ZM0p2TFhkbFltaHZiMnN0WTJFd0hoY05NalV3TlRNd01UWTFPVFUyV2hjTgpNelV3TlRJNE1UWTFPVFUyV2pBWk1SY3dGUVlEVlFRRERBNWpjbTh0ZDJWaWFHOXZheTFqWVRDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUpsRlU0SjFxR1hkK1BqcmxaWmpuNHF1RlJwcks5eXUKLytDQWp1alJnWFFhcStiNGVUSDNCaWxMOEQ3eGlPWkFmdmgzRm5SbWlVdjBObUNiSUdMVldQZXdIT0ZYWnBjRAorZVliZk9qS2UzUmFlcFhPdFRoU05tYmZkM1U3b0Q0U3hHUGY2RXRWeXUvUmlsck1tL3dOZ29BYWgrd1pKUGJLCks5M1JwK1ZFcTVuUDh1Y1ozQlFjRFlNaUJtYkYrTFNCdlkzNHdsZzliQk1xY0F6SUg5Zm15VU8rNTk4QTM5V3EKWG8rNDQ2ZDNaekRYVk4wbHFwRGM5MERhMlpTR2ZzM09RRWxmOWtLNG1PTVJCa1h0Z09IQVNSdUUvd3hSRVludgppczM0YjVOdTVvWVFndmcrNy9ZNnNPanp2SlNXM3VMbjhmektRay8zNm5BL2x4dHY3MDhxVmFVQ0F3RUFBYU5UCk1GRXdIUVlEVlIwT0JCWUVGRFdSTkl5UUV6cXZEdVFRQjRET25tbjFobzQ5TUI4R0ExVWRJd1FZTUJhQUZEV1IKTkl5UUV6cXZEdVFRQjRET25tbjFobzQ5TUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFCNWxyUGJLNVZDRDhWdnBndkU2V0NCQ1JWbEwvQU15RURkalFmeFFEM1lsZEljcXdnY3lITkZwCnRVM0JwR1NScFE1SU83SGYxZmZ6YTMybXA3YjJLUDBXMkFYa3hQZGtPeW5VMUQ4RGZYbXV3NDlKaHpFcGMwL0UKK2xTZkNEWnpkUVVyMXVwNGxvNUlOSlRaV3NhSE1wMnJacHduejJUMnRIZDZHaDdZV29lTFNvM3ZhQVYrNEFSSgorQmdpaU9kMlpnL0V1aE84ZENyYS9Mc2sxcVhib2hKZ213dEhIYTNnaUF4ZmpNcFdZdXlGN2hZUTl6V0ZUZ2Z3Ck43TjUxZXpxQmVDR3YrbG1ySmJWODlnbW5SWktMTml6aC9UelRjNkNHRWIyUklJWkJYWVpjUDJOOEd0LzJLdDcKYWowOVVsYlExTE9pajU3MldZNEI1OGhaeERIbXZZND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==

  hostAliases:
    - ip: 192.168.1.101
      hostnames:
        - cdimgr.localdomain