name: cdi-dra

createNamespace: true
namespace: composable-dra

replicaCount: 1

image: "10.38.251.227:5000/cdi-dra:v19-c6e55ba"
imagePullPolicy: IfNotPresent

env:
  USE_CAPI_BMH: "false"
  USE_CM: "false"
  SCAN_INTERVAL: "5s"

configmap:
  name: composable-dra-dds

secret:
  name: composable-dra-secret



