apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.systemNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/managed-by: Helm
    control-plane: controller-manager