{{- if .Values.credentials.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.credentials.namespace }}
---
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Values.credentials.namespace }}
type: Opaque
stringData:
  username: {{ .Values.global.credentials.username | quote }}
  password: {{ .Values.global.credentials.password | quote }}
  client_id: {{ .Values.global.credentials.client_id | quote }}
  client_secret: {{ .Values.global.credentials.client_secret | quote }}
  realm: {{ .Values.global.credentials.realm | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.tls.secretName }}
  namespace: {{ .Values.operator.systemNamespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{- nindent 4 .Values.webhook.tls.crt }}
  tls.key: |
{{- nindent 4 .Values.webhook.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.externalCA.secretName }}
  namespace: {{ .Values.operator.systemNamespace }}
type: Opaque
stringData:
  ca.crt: |
{{- nindent 4 .Values.global.credentials.certificate }}
