apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: composable-resource-operator-system
type: Opaque
stringData:
  username: {{ .Values.global.credentials.username | quote }}
  password: {{ .Values.global.credentials.password | quote }}
  client_id: {{ .Values.global.credentials.client_id | quote }}
  client_secret: {{ .Values.global.credentials.client_secret | quote }}
  realm: {{ .Values.global.credentials.realm | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: composable-resource-operator-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{- nindent 4 .Values.webhook.server.crt }}
  tls.key: |
{{- nindent 4 .Values.webhook.server.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: external-server-ca-cert
  namespace: composable-resource-operator-system
type: Opaque
stringData:
  ca.crt: |
{{- nindent 4 .Values.global.externalCA.certificate }}
