common:
  name: dynamic-device-scaler

  image: "10.38.251.227:5000/dds:latest"
  imagePullPolicy: IfNotPresent

  env:
    SCAN_INTERVAL: "10"
    DEVICE_NO_REMOVAL_DURATION: "10"
    DEVICE_NO_ALLOCATION_DURATION: "10"
